# MegaLinter configuration file
# More info at https://megalinter.io
APPLY_FIXES: all
SHOW_ELAPSED_TIME: true

# Exclude directories that should not be scanned
EXCLUDES:
  - node_modules
  - dist
  - .npm_cache
  - .git

# Disable specific linters that are redundant or too noisy for this initial phase
DISABLE_LINTERS:
  - REPOSITORY_GRYPE
  - REPOSITORY_GITLEAKS
  - REPOSITORY_CHECKOV
  - COPYPASTE_JSCPD
  - SPELL_CSPELL
  - SPELL_LYCHEE
  - MARKDOWN_MARKDOWN_LINK_CHECK
  - TYPESCRIPT_TS_STANDARD
  - JSON_PRETTIER
  - MARKDOWN_MARKDOWN_TABLE_FORMATTER
  - YAML_V8R
