#!/usr/bin/env node
// Sync src/version.ts to match the "version" field in package.json so the
// User-Agent header reports the right version at runtime. Run via the
// `prebuild` and `pretest` npm scripts; safe to run on its own.

import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const here = dirname(fileURLToPath(import.meta.url));
const repoRoot = join(here, "..");
const pkg = JSON.parse(readFileSync(join(repoRoot, "package.json"), "utf8"));
const version = pkg.version;

if (typeof version !== "string" || version.length === 0) {
  console.error("sync-version: package.json has no usable version field");
  process.exit(1);
}

const out = `/*
Copyright 2026 Expedia Group, Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Mirrors package.json "version". Regenerated by scripts/sync-version.mjs
// via the prebuild / pretest npm scripts — edit package.json, not this file.
export const PLUGIN_VERSION = ${JSON.stringify(version)};
`;

writeFileSync(join(repoRoot, "src", "version.ts"), out);
console.log(`sync-version: wrote src/version.ts (${version})`);
